# https://taskfile.dev

version: '3'


tasks:
  build:
    desc: Build for Docker Hub
    cmds:
      - docker build -t alastairhm/yamllint:latest ./
    silent: true
  push:
    desc: Push to Docker Hub
    cmds:
      - docker push alastairhm/yamllint:latest
    silent: true
